// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using admin_service.Data;

#nullable disable

namespace admin_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231123419_BusScheduleBaseline")]
    partial class BusScheduleBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("admin_service.Models.Bus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bus_name");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bus_number");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bus_type");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("Id");

                    b.HasIndex("BusNumber")
                        .IsUnique();

                    b.ToTable("buses");
                });

            modelBuilder.Entity("admin_service.Models.BusSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("arrival_time");

                    b.Property<long>("BusId")
                        .HasColumnType("bigint")
                        .HasColumnName("bus_id");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("departure_time");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("from_city");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("journey_date");

                    b.Property<double>("TicketPrice")
                        .HasColumnType("double")
                        .HasColumnName("ticket_price");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("to_city");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("bus_schedules");
                });

            modelBuilder.Entity("admin_service.Models.BusSchedule", b =>
                {
                    b.HasOne("admin_service.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });
#pragma warning restore 612, 618
        }
    }
}
