// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using admin_service.Data;

#nullable disable

namespace admin_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231120805_CreateBusTableV2")]
    partial class CreateBusTableV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("admin_service.Models.Bus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bus_name");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bus_number");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bus_type");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("Id");

                    b.HasIndex("BusNumber")
                        .IsUnique();

                    b.ToTable("buses");
                });
#pragma warning restore 612, 618
        }
    }
}
